spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: pcserver123.
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000
  thymeleaf:
    cache: true
cluster:
  isredis: true                      #是否开启redis缓存过滤请求
  isredistime: 7200                   #有效时间  单位s秒
  encrypt: true                      #是否启动加密
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.104.246.36:2468;databaseName=Posmanagement_main
    username: sa
    password: pcserver123.
server:
  port: 12379
  context-path: /Scan

logging:
  config: log4j.properties
  #src/main/resources/log4j.properties
  #下面可以不用管   需要的话可以开启
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: scan
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: scan
  company.name: www.hlyf.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@






